spring:
  datasource:
    url: jdbc:h2:~/test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    driver-class-name: org.h2.Driver  
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: ALWAYS
  sql:
    init:
      mode: always

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: /mapper/*.xml
  type-aliases-package: com.brand13.book_ex.vo
  
